server:
  port: 8761

##eureka server  
eureka:
  client:
    register-with-eureka: false 
    fetch-registry: false
    
##It is used the change the default port for eureka    
##eureka.client.service-url.defaultZone=http://localhost:8080/eureka