server:
  port: 9002
  
spring:
  application:
    name: API-GATEWAY
    ##cloud-configuration for hitting specific uri 
  cloud:
    gateway:
      routes:
      ##USER
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
           - Path=/user/**
        ##Circuit Breaker Hystrix   
        filters: 
        - name: CircuitBreaker
          args:
            name: USER-SERVICE
            fallbackuri: forward:/userServiceFallBackMethod  
        ##DEPARTMENT     
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
           - Path=/departments/** ##path
        ##Circuit Breaker Hystrix      
        filters:
        - name: CircuitBreaker
          args:
            name: DEPARTMENT-SERVICE
            fallbackuri: forward:/departmentServiceFallBackMethod
        
##Hystrix-configuration      
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
             
            
    
##eureka-clinent enable config    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
       hostname: 192.168.49.1
      